language: generic
os: 
  - osx

osx_image: xcode8

script:
- xcodebuild -workspace TABScrollingContentView.xcworkspace  -scheme TABScrollingContentView -configuration Debug -sdk iphonesimulator10.0 -destination "OS=10.0,name=iPhone 6s Plus"
